### ISSUE TITLE
Plex usage

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/webhook-events#1]
Hello, 
This adapter works fine when the external app calls several different URL, but for Plex, there is only one URL and the content message changes according to the action taken by user.

Example: 
The user starts playing a media, Plex will call the webhook with   "event": "media.play"  in the payload.
The user stops playing a media, Plex will call the webhook with   "event": "media.stop"  in the payload.

You can have a look at the doc here 
[https://support.plex.tv/articles/115002267687-webhooks/?utm_campaign=Plex%20Apps&utm_medium=Plex%20Web&utm_source=Plex%20Apps](url)

Maybe that for each webhook added in the adapter config, there could have a field in which we could specify the name of the property to look, and another field for the value.

Thanks

**Comment by mrstegeman** [comment]
Ok, I've completely reworked that add-on. Try out the new config and URLs and see what you think.

**Comment by soulfire03** [comment]
I did several tests but I was not able to change my lights state with the webhook.

I replaced the Url in Plex with the new one of the Thing;
Then I added property "event" in the settings;
And I added a rule with the event value "media.start";

Is it correct?
There is no log for the webhook Thing so it's hard to know what's wrong.

I checked the jwt in jwt.io and it says the signature part of the json token is incorrect. 
Let me know if I can do more tests for you

Thank you

**Comment by mrstegeman** [comment]
When you’re adding your new hook now:
1. The name is just something for you. That’s the name you’ll use when you’re creating rules.
2. The property key should be `event`.
3. The property value type should be `string`.

**Comment by mrstegeman** [comment]
The other thing to ensure is that Plex can reach your gateway. Make sure the host name part of the webhook URL is something accessible by Plex.

**Comment by mrstegeman** [comment]
And... make sure you copy the whole URL. It is quite long and will scroll off the screen.

**Comment by soulfire03** [comment]
These settings was good, and I use the webthings.io address for Plex so it should have access.

I made a test page to see what Plex was sending and I saw there is a container object before the event property.
   
`{"payload": {"event": "media.start", ...`

Can we put something like "payload.event" in the property key ?
Was it working for you as is?

**Comment by mrstegeman** [comment]
I don’t use Plex, so I was just doing some manual testing. I had considered nested keys, but couldn’t decide on a good way. Property keys _could_ have dots in them.

**Comment by soulfire03** [comment]
Well I tested `payload.event` in property key and it did nothing.. :(
I may be able to setup a debug environment to help you, but sadly I don't do python, and I'm a very beginner in node.js

**Comment by mrstegeman** [comment]
Yeah, that definitely won’t work without some changes to the add-on. I’ll try to do that tomorrow and let you know.

**Comment by mrstegeman** [comment]
Ok, give v0.2.0 a shot, with `payload.event` as the property key.

**Comment by soulfire03** [comment]
Unfortunately, my light did not change

**Comment by mrstegeman** [comment]
Can you see the webhook device’s property changing when Plex hits it?

**Comment by soulfire03** [comment]
No the device doesn't change in the app either.
I checked with fiddler to send some test requests and here are my findings...

It seems that the payload content is enclosed within quotes. 
  {"payload": " { \"event\": \"media.play\", ... } "}
I think you will need to json-decode the content before you work with it. To ensure that this plugin is as generic as possible, you could just check if the content is string or json object.

Next, I tried to send a post request without the quotes, and then I was able to get some logs in the webhook log:

plexmediaevent Il y a ⁨10⁩ minutes
data: media.play

Then in the rule : 
Initially, the rule was set to decrease brightness and I wanted to make sure the light would come On if it wasn't, so I made two output items. First one was to power on the light, Second was to set brightness to 20. 
Doing this, the light was always keeping a 100% brightness.
I found that if I removed the first property change and keeping only the brightness change, then it worked.

So there is two problems here. The quotes, and the fact that setting two property change for a rule seems to not work.
My device is Lifx White DawnDusk bulb, so maybe when we send a power on, the device does a 100% brightness at same time. Maybe ordering the properties execution might do the trick.

**Comment by soulfire03** [comment]
Well, after removing the power ON property change in my rule and adding it back again, it worked with using fiddler, so the second problem is no more!

**Comment by mrstegeman** [comment]
Ok, so the main problem then is that Plex encodes the body improperly. That is... annoying.

**Comment by mrstegeman** [comment]
v0.3.0 should work for you. Change your property key to `event`, rather than `payload.event`.

**Comment by soulfire03** [comment]
Yes sir, Finally it's working great!
Thank you for the time you took on this case, and thanks to the team who put together this app, the potential is awesome.

**Comment by mrstegeman** [comment]
Glad it's working!
