### ISSUE TITLE
Multiple property key for the same hook ID

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/webhook-events#2]
Hi Michael !
I would like to be able to set more than one property key for the same hook unique ID.

The case is that when I start playback on the Plex app on my phone, I don't want the lights in the living room to open or close. So I need to add a condition in my rules to check the player device name.

**Comment by mrstegeman** [comment]
This seems feasible. I'll look into it soon.

**Comment by mrstegeman** [comment]
This should now be supported in v0.4.0.

**Comment by soulfire03** [comment]
The change is working great, thank you!
